server:
  port: ":3000"
  app_name: "systradex"
  jwt_secret: "hhwtrade-secret-key-2025"  

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "format"
  dbname: "systradex"
  sslmode: "disable"
  timezone: "Asia/Shanghai"
  table_prefix: "future_"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
