server:
  port: ":3000"
  app_name: "systradex"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "format"
  dbname: "systradex"
  sslmode: "disable"
  timezone: "Asia/Shanghai"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
